version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: bitrix-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - bitrix_network

  php:
    build: bitrix-php
    container_name: bitrix-php
    volumes:
      - ../src:/var/www/html
      - ./bitrix-php/www.conf:/etc/php/8.3/fpm/pool.d/www.conf
    expose:
      - "9000"
    networks:
      - bitrix_network

  db:
    image: mariadb:latest
    container_name: bitrix-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bitrix
      MYSQL_USER: bitrix
      MYSQL_PASSWORD: bitrix
    volumes:
      - ../db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - bitrix_network
  redis:
    image: redis:latest
    container_name: bitrix-redis
    restart: always
    networks:
      - bitrix_network
  websocket-server:
    build: ./nodejs
    container_name: websocket-server
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=supersecretkey
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ../websocker-server/:/app
    networks:
      - bitrix_network

volumes:
  db_data:

networks:
  bitrix_network:
